services:
  - type: web
    plan: free
    name: megaX
    env: node
    buildCommand: yarn
    startCommand: node index.js
    repo: https://github.com/Ravindu12123/MegaX    
    branch: main
    autoDeploy: false
